---
title: "DataVisExample"
author: "Richard"
date: "2022-10-18"
output: rmarkdown::github_document
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Installing packages}
install.packages("tidyverse")
```

```{r Import libraries}
library(ggplot2)
library(ggmap)
```

```{r Read in dataset}
cdat <- read.csv("anon_gps_tracks_with_dive.csv")
```

```{r Create bounding box and retrieve satellite map based on latitude and longitude}
cbbox <- make_bbox(lon = cdat$lon, lat = cdat$lat)
sq_map <- get_map(location = cbbox, maptype = "satellite", source = "google")
```

```{r Overlay all bird tracks on the map}
ggmap(sq_map) + 
  geom_path(data = cdat, aes(x = lon, y = lat, color = species), 
            size = 0.5, lineend = "round") +
  labs(x = " ", y = " ", title = "Inividual tracks", color = "Legend") 
  theme_minimal() +
  theme(legend.position = "none")
```

```{r Overlay tRAZO birds from colony 2 onto map}
c1 <- cdat[cdat$colony2 %in% "2" & cdat$species %in% "tRAZO", ]
cbbox2 <- make_bbox(lon = c1$lon, lat = c1$lat)
sq_map2 <- get_map(location = cbbox2, maptype = "satellite", source = "google")
ggmap(sq_map2) + 
  geom_path(data = c1, aes(x = lon, y = lat, color = X), 
            size = 0.5, lineend = "round") +
  labs(x = " ", y = " ", title = "tRAZO in Colony 2", color = "Time") 
  theme_minimal() +
  theme(legend.position = "none")
```

```{r Basic violin plot for longitude across species}
p <- ggplot(cdat, aes(x=species, y=lon, color = species)) + 
  geom_violin()
p
```

```{r Advanced violin plot for latitude across species}
library(ggsignif)
p <- ggplot(c, aes(x=species, y=lat, fill = species)) + 
  geom_violin(trim = FALSE)+
  geom_boxplot(width=0.1, alpha=0.5) +
  scale_fill_manual(values=c("#3D5A80", "#98C1D9", "#E0FBFC"))+
  geom_signif(comparisons = list(c("tRAZO", "tEUSH")), 
              map_signif_level=TRUE, y_position = 61)+
  geom_signif(comparisons = list(c("tCOGU", "tRAZO")), 
              map_signif_level=TRUE, y_position = 62)+
  labs(x="Species", y="Latitude", fill="Species")+
  theme_minimal()
p
```
